eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8081
env: dev
spring:
  rabbitmq:
    host: 118.178.186.197
    port: 5672
    username: admin
    password: admin
